### ISSUE TITLE
An error occurs when opening the page

### ISSUE THREAD

**Issue by xiehongyu2005** [doccano/doccano-mini#30]
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/6913924/228790150-2f923f00-9e4a-4a9d-b63a-e9984eb8fc4a.png">

**Comment by Hironsan** [comment]
Related to https://github.com/hwchase17/langchain/issues/1913.
What is your pydantic version? I'm ok with `pydantic==1.10.7`.
